# theme: jekyll-theme-minimal # jekyll-theme-cayman

theme: blogbox-jekyll-theme
title: KidsVerve Coding Homepage
description: KidsVerve Coding site aims to introduce children to computer coding and the fundamental concepts in this field. 🌟 