# theme: jekyll-theme-minimal # jekyll-theme-cayman # blogbox-jekyll-theme
theme: jekyll-theme-cayman-blog
title: KidsVerve Coding Homepage
description: KidsVerve Coding site aims to introduce children to computer coding and the fundamental concepts in this field. 🌟 