# theme: jekyll-theme-minimal # jekyll-theme-cayman # blogbox-jekyll-theme

# theme: creative-theme-jekyll
# theme: jekyll-theme-time-machine
theme: jekyll-theme-hyde
title: KidsVerve Coding Homepage
description: KidsVerve Coding site aims to introduce children to computer coding and the fundamental concepts in this field. 🌟 